// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohmneverymagclcqclw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaG1uZXZlcnltYWdjbGNxY2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzIyOTksImV4cCI6MjA2MDAwODI5OX0.vEn4cB7Kf0JDiWiuGCyOnycHfaLHRA6Vkh0WuFhN0kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);